api_platform:
    title: Product Api 
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/config/api_platform/resources']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
