author:  Maxim Yalagin <yalagin@gmail.com>
id:
    generationStrategy: uuid
    writable: true
rdfa:
    #-  uri: "https://schema.org/docs/schema_org_rdfa.html" # Current version of Schema.org
    #    format: rdfa
    #-   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/ext/auto/auto.rdfa" # Experimental version of Schema.org extension: AUTO
    #    format: rdfa
    -   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/3.7/all-layers.rdf" # Current version of Schema.org + all extensions
        format: rdf
    -   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/schema.rdfa" # Experimental version of Schema.org
        format: rdfa
types:
    Product:
        properties:
            name: { range: "Text" }
            price: { range: "Text" }
            priceCurrency: { range: "Text" }
        
